version: 2

models:
  - name: raw_products
    description: "Raw JSON variant column and file name loaded from dummyjson API for products"
    columns:
      - name: json_data
        description: "VARIANT column containing the full JSON payload for products"
        tests:
          - not_null
      - name: file_name
        description: "Name of the JSON file ingested for this products payload"
        tests:
          - not_null
          - unique
