
name: dummyjson_to_snowflake_dbt
version: '1.0'
config-version: 2

profile: user

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  int:
    carts:
      +materialized: view
    products:
      +materialized: view
    users:
      +materialized: view
  marts:
    carts:
      +materialized: view
    products:
      +materialized: view
    users:
      +materialized: view
  raw:
    carts:
      +materialized: view
    products:
      +materialized: view
    users:
      +materialized: view

