name: dummyjson_to_snowflake_dbt
version: '1.0'
config-version: 2

profile: user

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  dummyjson_to_snowflake_dbt:
    raw:
      +materialized: view
      carts:
      carts_products:
      products:
      users:
    stg:
      +materialized: view
      carts:
      carts_products:
      products:
      users:
    int:
      +materialized: view
      carts:
      carts_products:
      products:
      users:
    mart:
      +materialized: table
      carts:
      carts_products:
      products:
      users:
