name: dummyjson_to_snowflake_dbt
version: '1.0'
config-version: 2

profile: user

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  dummyjson_to_snowflake_dbt:    # Project navn her
    raw:                         # Rå-data
      +materialized: view
      carts:
      products:
      users:
    stg:                         # Staging‐lag
      +materialized: view
      carts:
      products:
      users:
    int:                         # Intermediate‐lag
      +materialized: view
      carts:
      products:
      users:
    marts:                       # Mart‐lag
      +materialized: view
      carts:
      products:
      users:
