name: 'dummyjson_to_snowflake_dbt'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dummyjson_to_snowflake_dbt:
    raw:
      +materialized: view
    stg:
      +materialized: view
    int:
      +materialized: view
    marts:
      +materialized: table
