version: 2

models:
  - name: stg_users
    description: "Staging model for users: one row per user from the latest JSON file"
    columns:
      - name: user_id
        description: "Unique identifier for the user"
        tests:
          - not_null
      - name: first_name
        description: "User’s first name"
        tests:
          - not_null
      - name: last_name
        description: "User’s last name"
        tests:
          - not_null
      - name: email
        description: "User’s email address"
        tests:
          - not_null
      - name: age
        description: "User’s age"
      - name: gender
        description: "User’s gender"
      - name: phone
        description: "User’s phone number"
      - name: city
        description: "City where the user lives"
      - name: postal_code
        description: "Postal code for the user’s address"
      - name: company_name
        description: "Name of the company the user works for"
     
