version: 2

models:
  - name: int_products
    description: "Intermediate-modell for produktdata med prisberegninger"
    columns:
      - name: product_id
        tests:
          - not_null
          - unique
      - name: discounted_price
        tests:
          - not_null
      - name: stock_status
        tests:
          - not_null
          - accepted_values:
              values: ['out_of_stock', 'low_stock', 'in_stock']
      - name: category
      - name: brand
      - name: price
        tests:
          - not_null
      - name: discount_percentage
        tests:
          - not_null
