version: 2

models:
  - name: stg_products
    description: "Staging model for products: one row per product from the latest JSON file"
    columns:
      - name: product_id
        description: "Unique identifier for the product"
        tests:
          - not_null
      - name: title
        description: "Product title"
        tests:
          - not_null
      - name: description
        description: "Product description"
      - name: price
        description: "Original price of the product"
        tests:
          - not_null
      - name: discount_percentage
        description: "Discount percentage applied to the product"
      - name: rating
        description: "Customer rating for the product"
      - name: stock
        description: "Number of items in stock"
      - name: brand
        description: "Brand name of the product"
      - name: category
        description: "Category of the product"