version: 2

models:
  - name: fact_carts_products
    description: "Fact table for cart line items (one row per product in a cart)"
    columns:
      - name: cart_id
        description: "Foreign key to fact_carts.cart_id"
        tests:
          - not_null
      - name: product_id
        description: "Foreign key to dim_products.id"
        tests:
          - not_null
      - name: quantity
        description: "Number of units of this product in the cart"
        tests:
          - not_null
      - name: item_total
        description: "Extended total for this line (quantity × discounted_price)"
        tests:
          - not_null
