-- Opprett database om den ikke finnes
CREATE DATABASE IF NOT EXISTS DUMMYJSON_PIPELINE;
USE DATABASE DUMMYJSON_PIPELINE;

-- Opprett schema for rådata
CREATE SCHEMA IF NOT EXISTS RAW_STAGE;
USE SCHEMA RAW_STAGE;
